# Generated by Django 4.1.2 on 2022-11-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
