# Generated by Django 4.1.2 on 2022-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0002_course_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
