# Generated by Django 4.1.2 on 2022-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0003_unit_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[("1", "Beginner"), ("2", "Intermediate"), ("3", "Advanced")],
                default="1",
                max_length=2,
            ),
        ),
    ]
