# Generated by Django 4.1.2 on 2022-11-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0004_remove_unit_difficulty_course_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="sign_language_app.course",
            ),
            preserve_default=False,
        ),
    ]
