# Generated by Django 4.1.2 on 2022-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0005_unit_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["-ordering_number"]},
        ),
        migrations.AddField(
            model_name="unit",
            name="ordering_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
