# Generated by Django 4.1.2 on 2022-11-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0006_alter_unit_options_unit_ordering_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["-ordering_number"]},
        ),
    ]
