# Generated by Django 4.1.2 on 2022-11-18 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sign_language_app", "0009_unitattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitattempt",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unite_attempts",
                to="sign_language_app.unit",
            ),
        ),
        migrations.AlterField(
            model_name="unitattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unite_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
