# Generated by Django 4.1.2 on 2022-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0011_alter_unitattempt_unit_alter_unitattempt_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GestureLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="gesture",
            name="locations",
            field=models.ManyToManyField(to="sign_language_app.gesturelocation"),
        ),
    ]
