# Generated by Django 4.1.2 on 2022-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0012_gesturelocation_gesture_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="gesture",
            name="left_hand",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gesture",
            name="right_hand",
            field=models.BooleanField(default=True),
        ),
    ]
