# Generated by Django 4.1.2 on 2022-12-17 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sign_language_app", "0013_gesture_left_hand_gesture_right_hand"),
    ]

    operations = [
        migrations.AddField(
            model_name="gesture",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gesture",
            name="status",
            field=models.CharField(
                choices=[("0", "Pending"), ("1", "Complete")], default="1", max_length=1
            ),
        ),
    ]
