# Generated by Django 4.1.2 on 2022-12-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_language_app', '0017_remove_course_is_public_course_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
    ]
