# Generated by Django 4.1.2 on 2022-12-31 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sign_language_app", "0021_alter_studentsaccess_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsaccess",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentsaccess",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
