# Generated by Django 4.1.2 on 2023-01-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0025_remove_unitattempt_score_gestureattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitattempt",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gestureattempt",
            name="unit_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gesture_attempts",
                to="sign_language_app.unitattempt",
            ),
        ),
    ]
