# Generated by Django 4.1.2 on 2023-01-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_language_app', '0027_alter_unitattempt_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestureattempt',
            old_name='attempts',
            new_name='attempt',
        ),
    ]
