# Generated by Django 4.1.2 on 2023-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_language_app', '0028_rename_attempts_gestureattempt_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestureattempt',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
