# Generated by Django 4.1.2 on 2023-01-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_language_app', '0029_gestureattempt_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestureattempt',
            options={'ordering': ['id', 'attempt']},
        ),
    ]
