# Generated by Django 4.1.5 on 2023-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0031_gestureattempt_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="can_train_on_videos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="can_view_videos",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gesture",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Pending"),
                    ("1", "Training"),
                    ("2", "Complete"),
                    ("3", "Pending Deletion"),
                ],
                default="2",
                max_length=1,
            ),
        ),
    ]
