# Generated by Django 4.1.5 on 2023-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0032_usersettings_can_train_on_videos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitattempt",
            name="is_overruled",
            field=models.BooleanField(default=False),
        ),
    ]
