# Generated by Django 4.1.5 on 2023-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0033_unitattempt_is_overruled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="can_train_on_videos",
            new_name="allow_video_training",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="can_view_videos",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="allow_sharing_with_teachers",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="allow_video_uploads",
            field=models.BooleanField(default=True),
        ),
    ]
