# Generated by Django 4.1.5 on 2023-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_language_app", "0035_gestureattempt_added_to_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="avatar",
            field=models.ImageField(default=None, null=True, upload_to="avatars"),
        ),
    ]
