version: '0.1'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
#    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db