version: '2.1'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    healthcheck:
      # Checks if the database has started and in ready to accept connections.
      # Source: https://stackoverflow.com/a/55835081/5165250
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    environment:
      - NGINX_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
#      - media_volume:/media
    depends_on:
      - web

  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/data/static
#      - media_volume:/code/sl_ai/ai_data
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy


volumes:
  redis_data:
  # Django copies/compiles the static files and shares them with the nginx container using a volume.
  static_volume:
  media_volume: