version: '0.1'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server
    #    command: redis-server --appendonly yes
    #    command: redis-server --protected-mode no CONFIG SET protected-mode no
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
#    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - "db"

volumes:
  redis_data: